// constants/games.ts
// Single source of truth for game metadata.
// Add/remove/edit a game here and every screen (Hub, Games list, game page,
// leaderboard, achievements) picks it up automatically — nothing else to touch.

export interface GameDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  tag: { label: string; color: string };
  badge: string;
  difficulty: string;
  barColor: string;
  /** iframe path for legacy (non-React) games; omitted for React-component games */
  url: string;
  /** true for the small set of recently-added games shown in the "New" row */
  isNew: boolean;
}

export const GAMES: GameDefinition[] = [
  { id: 'unicorn', name: 'Unicorn Trophy Run', icon: '🦄', description: 'Fast vocabulary matching with bright visuals and quick recall pressure.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: '3 Levels', difficulty: 'Starter', barColor: 'var(--gold)', url: 'games/unicorn-run/unicorn.html', isNew: false },
  { id: 'warriors', name: 'Grammar Hoop Slam', icon: '🏀', description: 'Train tense accuracy with increasingly challenging sentence choices.', tag: { label: 'Grammar', color: 'tag-grammar' }, badge: '3 Levels', difficulty: 'Intermediate', barColor: 'var(--green)', url: 'games/grammar-hoop-slam/grammar-hoop-slam.html', isNew: false },
  { id: 'compound', name: 'Compound Word Quest', icon: '🧩', description: 'Strengthen word-building intuition by combining clues into full answers.', tag: { label: 'Word Formation', color: 'tag-words' }, badge: 'Word Fusion', difficulty: 'Puzzle', barColor: 'var(--blue)', url: 'games/compound-word-quest/compound.html', isNew: false },
  { id: 'wordmatch', name: 'Word Match', icon: '🔤', description: 'Match words to their meanings in a fast-paced pairing challenge.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Match Up', difficulty: 'Starter', barColor: 'var(--purple)', url: 'games/word-match/index.html', isNew: false },
  { id: 'memory', name: 'Memory Game', icon: '🧠', description: 'Flip cards and match pairs to sharpen recall and vocabulary retention.', tag: { label: 'Memory', color: 'tag-grammar' }, badge: 'Flip & Match', difficulty: 'Starter', barColor: 'var(--coral)', url: 'games/memory-game/index.html', isNew: false },
  { id: 'missingfruit', name: 'Missing Fruit', icon: '🍓', description: 'Identify the missing item from the sequence to build observation and logic skills.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Spot It', difficulty: 'Puzzle', barColor: 'var(--green)', url: 'games/missing-fruit/index.html', isNew: false },
  { id: 'animalclass', name: 'Animal Class Quest', icon: '🦁', description: 'Sort creatures into their correct animal classes in this science-meets-ESL challenge.', tag: { label: 'Science', color: 'tag-bio' }, badge: 'Classify', difficulty: 'Starter', barColor: 'var(--teal)', url: 'games/animal-class-quest/animal-class-quest.html', isNew: false },
  { id: 'colourclash', name: 'Colour Clash', icon: '🎨', description: 'Identify and match colours at speed — great for early learners and visual thinkers.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Colours', difficulty: 'Starter', barColor: 'var(--purple)', url: 'games/colour-clash/colour-clash.html', isNew: false },
  { id: 'crimsonduel', name: 'Crimson Color Duel', icon: '⚔️', description: 'Two-player colour duel mode — compete head-to-head to name colours fastest.', tag: { label: 'Colours', color: 'tag-vocab' }, badge: 'Duel', difficulty: 'Competitive', barColor: 'var(--red)', url: 'games/crimson-color-duel/crimson-color-duel-premium.html', isNew: false },
  { id: 'deepseaReveal', name: 'Deep Sea Reveal', icon: '🌊', description: 'Uncover hidden ocean creatures as you answer vocabulary questions correctly.', tag: { label: 'Science', color: 'tag-bio' }, badge: 'Reveal', difficulty: 'Mixed Skills', barColor: 'var(--teal)', url: 'games/deep-sea-reveal/deep-sea-reveal.html', isNew: false },
  { id: 'emojimatch', name: 'Emoji Match', icon: '😊', description: 'Match emojis to their English words in this fun and expressive memory challenge.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Match Up', difficulty: 'Starter', barColor: 'var(--gold)', url: 'games/emoji-match/emoji-match.html', isNew: false },
  { id: 'emojispelling', name: 'Emoji Spelling Game', icon: '📝', description: 'Use emoji clues to practise spelling and reinforce word-sound connections.', tag: { label: 'Spelling', color: 'tag-words' }, badge: 'Spell It', difficulty: 'Intermediate', barColor: 'var(--purple)', url: 'games/emoji-spelling-game/emoji_spelling_game.html', isNew: false },
  { id: 'familyquest', name: 'Family Quest', icon: '👨‍👩‍👧', description: 'Learn family member vocabulary and relationships through an interactive quest format.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Family', difficulty: 'Starter', barColor: 'var(--green)', url: 'games/family-quest/family-quest-premium.html', isNew: false },
  { id: 'farmgame', name: 'Farm Game', icon: '🌾', description: 'Explore farm life vocabulary through an engaging game-based learning experience.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Farm Life', difficulty: 'Starter', barColor: 'var(--gold)', url: 'games/farm-game/farm-game-v1.html', isNew: false },
  { id: 'findmyfood', name: 'Find My Food', icon: '🍔', description: 'Spot and identify foods from descriptions — builds food vocabulary and reading skills.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Find It', difficulty: 'Starter', barColor: 'var(--coral)', url: 'games/find-my-food/find-my-food-premium.html', isNew: false },
  { id: 'flagmaster', name: 'Flagmaster', icon: '🚩', description: 'Identify world flags and their countries — a geography and culture vocabulary boost.', tag: { label: 'Geography', color: 'tag-bio' }, badge: 'Flags', difficulty: 'Intermediate', barColor: 'var(--blue)', url: 'games/flagmaster/flagmaster-premium.html', isNew: false },
  { id: 'foodwordhunt', name: 'Food Word Hunt', icon: '🍕', description: 'Hunt for hidden food words in a grid — combines spelling skills with vocabulary building.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Hunt', difficulty: 'Puzzle', barColor: 'var(--coral)', url: 'games/food-word-hunt/food-word-hunt.html', isNew: false },
  { id: 'fruitwordhunt', name: 'Fruit Word Hunt', icon: '🍎', description: 'Find fruit names hidden in a letter grid and sharpen your spelling at the same time.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Hunt', difficulty: 'Puzzle', barColor: 'var(--green)', url: 'games/fruit-word-hunt/fruit-word-hunt.html', isNew: false },
  { id: 'lakersracer', name: 'Lakers Showtime Racer', icon: '🏀', description: 'Race to the basket by answering correctly — fast-paced vocabulary and grammar sprints.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Race', difficulty: 'Competitive', barColor: 'var(--gold)', url: 'games/lakers-showtime-racer/lakers-showtime-racer.html', isNew: false },
  { id: 'neonbridge', name: 'Neon Bridge of Destiny', icon: '🌉', description: 'Cross the neon bridge by choosing the correct answer before time runs out.', tag: { label: 'Grammar', color: 'tag-grammar' }, badge: 'Survive', difficulty: 'Intermediate', barColor: 'var(--purple)', url: 'games/neon-bridge-of-destiny/neon-bridge-of-destiny.html', isNew: false },
  { id: 'oceanquest', name: 'Ocean Quest', icon: '🐠', description: 'Dive into ocean science vocabulary with this colourful underwater classification quest.', tag: { label: 'Science', color: 'tag-bio' }, badge: 'Dive In', difficulty: 'Mixed Skills', barColor: 'var(--teal)', url: 'games/ocean-quest/ocean-quest.html', isNew: false },
  { id: 'pacman', name: 'Pac-Man', icon: '👾', description: 'Classic arcade action with an ESL twist — chomp your way through vocabulary challenges.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Arcade', difficulty: 'Arcade', barColor: 'var(--gold)', url: 'games/pac-man/pac-man.html', isNew: false },
  { id: 'phonicsadventure', name: 'Phonics Adventure', icon: '📖', description: 'Go on a phonics journey, practising letter sounds and blends through story-driven play.', tag: { label: 'Phonics', color: 'tag-words' }, badge: 'Phonics', difficulty: 'Starter', barColor: 'var(--blue)', url: 'games/phonics-adventure/phonics-adventure.html', isNew: false },
  { id: 'phonicsworld', name: 'Phonics World', icon: '🔤', description: 'Explore a world of letter-sound relationships — ideal for early readers building fluency.', tag: { label: 'Phonics', color: 'tag-words' }, badge: 'Sounds', difficulty: 'Starter', barColor: 'var(--blue)', url: 'games/phonics-world/phonics-world.html', isNew: false },
  { id: 'shuttlecock', name: 'Shuttlecock Smash', icon: '🏸', description: 'Rally your vocabulary knowledge in this badminton-inspired word-smashing challenge.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Smash', difficulty: 'Competitive', barColor: 'var(--green)', url: 'games/shuttlecock-smash/shuttlecock-smash.html', isNew: false },
  { id: 'tornado', name: 'Tornado', icon: '🌪️', description: 'A whirlwind vocab challenge — answer before the storm sweeps your score away.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Storm', difficulty: 'Intermediate', barColor: 'var(--red)', url: 'games/tornado/tornado.html', isNew: false },
  { id: 'wgrandprix', name: 'W Grand Prix', icon: '🏎️', description: 'Rev up your vocabulary and race to the finish — the faster you answer, the further you go.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Race', difficulty: 'Competitive', barColor: 'var(--red)', url: 'games/w-grand-prix/w-grand-prix.html', isNew: false },
  { id: 'countadd', name: 'Count & Add', icon: '➕', description: 'Practise quick counting and addition with bright, early-numeracy questions.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Add Up', difficulty: 'Starter', barColor: 'var(--green)', url: 'assets/legacy-games/count-and-add/count-and-add.html', isNew: true },
  { id: 'moneyblocks', name: 'Money Blocks', icon: '💰', description: 'Reveal money blocks, manage risk, and race to build the biggest total.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Money', difficulty: 'Mixed Skills', barColor: 'var(--gold)', url: 'assets/legacy-games/money-blocks/index.html', isNew: true },
  { id: 'parachutedrop', name: 'Parachute Drop', icon: '🪂', description: 'Roll, stop, and choose parachute values in a playful two-player number game.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Dice', difficulty: 'Starter', barColor: 'var(--blue)', url: 'assets/legacy-games/parachute-drop/index.html', isNew: true },
  { id: 'superwings', name: 'Super Wings Races', icon: '✈️', description: 'Race colourful planes around the board in a simple turn-based classroom game.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Race', difficulty: 'Starter', barColor: 'var(--red)', url: 'assets/legacy-games/super-wings-game/index.html', isNew: true },
  { id: 'swampjump', name: 'Froggy Hop', icon: '🐸', description: 'Hop through the swamp, time each jump, and chase a new high score.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Hop', difficulty: 'Arcade', barColor: 'var(--green)', url: 'assets/legacy-games/swamp-jump-game/index.html', isNew: true },
  { id: 'treasurechest', name: 'Treasure Chest Showdown', icon: '🏴‍☠️', description: 'Choose treasure chests, collect rewards, and compete for the biggest hoard.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Treasure', difficulty: 'Competitive', barColor: 'var(--gold)', url: 'assets/legacy-games/treasure-chest-game/index.html', isNew: true },
  { id: 'unicornwings', name: 'Unicorn Wing Races', icon: '🦄', description: 'Race unicorns around the board with a sparkling two-player dice challenge.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Race', difficulty: 'Starter', barColor: 'var(--purple)', url: 'assets/legacy-games/unicorn-wings-game/index.html', isNew: true },
  { id: 'connect4', name: 'Connect 4', icon: '🔴', description: 'Classic four-in-a-row strategy — drop discs and outplan your opponent or the AI.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Strategy', difficulty: 'Competitive', barColor: 'var(--red)', url: 'games/connect-4/connect-4.html', isNew: true },
  { id: 'monkeytree', name: 'Monkey Tree Climb', icon: '🐒', description: 'Climb branch by branch, solving addition, subtraction, and multiplication to reach the summit.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Climb', difficulty: 'Mixed Skills', barColor: 'var(--green)', url: 'games/monkey-tree-climb/monkey-tree-climb.html', isNew: true },
  { id: 'blockfight', name: 'Block Fight', icon: '🥊', description: 'Run, jump, and battle through platform levels collecting rewards and defeating enemies.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Platformer', difficulty: 'Arcade', barColor: 'var(--coral)', url: 'games/block-fight/block-fight.html', isNew: true },
  { id: 'higherorlower', name: 'Higher or Lower', icon: '🃏', description: 'Guess whether the next card is higher or lower and build your streak.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Guess', difficulty: 'Puzzle', barColor: 'var(--red)', url: 'assets/legacy-games/higher-or-lower/index.html', isNew: true },
  { id: 'sentencebuilder', name: 'Sentence Builder', icon: '📝', description: 'Arrange scrambled words into correct sentences to sharpen grammar and word order.', tag: { label: 'Grammar', color: 'tag-grammar' }, badge: 'Build It', difficulty: 'Intermediate', barColor: 'var(--blue)', url: 'assets/legacy-games/sentence-builder/index.html', isNew: true },
  { id: 'redorblack', name: 'Red or Black', icon: '🎴', description: 'Call red or black before each card flips — a fast-paced game of odds and nerve.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Call It', difficulty: 'Competitive', barColor: 'var(--red)', url: 'assets/legacy-games/red-or-black/index.html', isNew: true },
  { id: 'picturerace', name: 'Picture Race', icon: '🏁', description: 'Race against the clock matching pictures to their English words.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Race', difficulty: 'Starter', barColor: 'var(--gold)', url: 'assets/legacy-games/picture-race/index.html', isNew: true },
  { id: 'feedmonster', name: 'Feed the Monster', icon: '👾', description: 'Count out the right number of apples to satisfy the hungry monster.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Count', difficulty: 'Starter', barColor: 'var(--green)', url: 'assets/legacy-games/feed-the-monster/index.html', isNew: true },
  { id: 'whatami', name: 'Field Guide: What Am I?', icon: '🔎', description: 'Study the clues and identify the mystery creature or object before you run out of guesses.', tag: { label: 'Vocabulary', color: 'tag-vocab' }, badge: 'Guess It', difficulty: 'Puzzle', barColor: 'var(--green)', url: 'assets/legacy-games/what-am-i/index.html', isNew: true },
  { id: 'whatsmissing', name: "What's Missing?", icon: '🧐', description: 'Study the picture, then spot what disappeared to sharpen memory and observation skills.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Spot It', difficulty: 'Puzzle', barColor: 'var(--blue)', url: 'assets/legacy-games/whats-missing/index.html', isNew: true },
  { id: 'tilebattle', name: 'Tile Battle', icon: '🀄', description: 'Face off over a grid of tiles in a fast, competitive matching showdown.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Battle', difficulty: 'Competitive', barColor: 'var(--red)', url: 'assets/legacy-games/tile-battle/index.html', isNew: true },
  { id: 'tictacroll', name: 'Tic·Tac·Roll — Premium Edition', icon: '🎲', description: 'A polished twist on tic-tac-toe with dice rolls raising the stakes each turn.', tag: { label: 'Logic', color: 'tag-bio' }, badge: 'Strategy', difficulty: 'Competitive', barColor: 'var(--purple)', url: 'assets/legacy-games/tictacroll/index.html', isNew: true },
];
