// games/catalog.data.ts
// SINGLE SOURCE OF TRUTH for game metadata.
// Every game the site knows about is one entry in GAME_CATALOG below.
// To add a game: add ONE entry here (plus its component in catalog.components.tsx
// if it's a React game). Run `npm run check-games` to verify nothing drifted.

export interface GameCatalogEntry {
  name: string;
  icon: string;
  desc: string;
  cover: string;
  tag: { label: string; color: string };
  badge: string;
  difficulty: string;
  barColor: string;
  isNew?: boolean;
  /** true if this game renders as a React component (see catalog.components.tsx) */
  hasComponent: boolean;
  /** iframe src, only set for legacy HTML games with no React component */
  legacyUrl?: string;
}

export const GAME_CATALOG: Record<string, GameCatalogEntry> = {
  tilebattle: {
    name: "Tile Battle",
    icon: "⚔️",
    desc: "A two-player local battle — flip tiles to trigger attacks, heals, and lifesteal until one warrior falls.",
    cover: "/assets/covers/tile-battle-cover.webp",
    tag: { label: "Strategy", color: "tag-bio" },
    badge: "PvP",
    difficulty: "Competitive",
    barColor: "var(--purple)",
    hasComponent: true,
  },
  quiztrail: {
    name: "Quiz Trail",
    icon: "🧠",
    desc: "Answer general-knowledge questions across a 10-level trail, racing against the clock.",
    cover: "/assets/covers/quiz-trail-cover.webp",
    tag: { label: "General Knowledge", color: "tag-bio" },
    badge: "10 Levels",
    difficulty: "Mixed Skills",
    barColor: "var(--gold)",
    isNew: true,
    hasComponent: true,
  },
  unicorn: {
    name: "Unicorn Trophy Run",
    icon: "🦄",
    desc: "Fast vocabulary matching with bright visuals and quick recall pressure.",
    cover: "/assets/covers/unicorn-trophy-race-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "3 Levels",
    difficulty: "Starter",
    barColor: "var(--gold)",
    hasComponent: true,
  },
  warriors: {
    name: "Warriors Grammar Slam",
    icon: "🏀",
    desc: "Train tense accuracy with increasingly challenging sentence choices.",
    cover: "/assets/covers/grammar-hoop-slam-cover.webp",
    tag: { label: "Grammar", color: "tag-grammar" },
    badge: "3 Levels",
    difficulty: "Intermediate",
    barColor: "var(--green)",
    hasComponent: true,
  },
  compound: {
    name: "Compound Word Quest",
    icon: "🧩",
    desc: "Strengthen word-building intuition by combining clues into full answers.",
    cover: "/assets/covers/compound-word-quest.webp",
    tag: { label: "Word Formation", color: "tag-words" },
    badge: "Word Fusion",
    difficulty: "Puzzle",
    barColor: "var(--blue)",
    hasComponent: true,
  },
  wordmatch: {
    name: "Word Match",
    icon: "🔤",
    desc: "Match words to their meanings in a fast-paced pairing challenge.",
    cover: "/assets/covers/word-match-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Match Up",
    difficulty: "Starter",
    barColor: "var(--purple)",
    hasComponent: true,
  },
  memory: {
    name: "Memory Game",
    icon: "🧠",
    desc: "Flip cards and match pairs to sharpen recall and vocabulary retention.",
    cover: "/assets/covers/memory-match-cover.webp",
    tag: { label: "Memory", color: "tag-grammar" },
    badge: "Flip & Match",
    difficulty: "Starter",
    barColor: "var(--coral)",
    hasComponent: true,
  },
  missingfruit: {
    name: "Missing Fruit",
    icon: "🍓",
    desc: "Identify the missing item from the sequence to build observation and logic skills.",
    cover: "/assets/covers/missing-fruit-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Spot It",
    difficulty: "Puzzle",
    barColor: "var(--green)",
    hasComponent: true,
  },
  animalclass: {
    name: "Animal Class Quest",
    icon: "🦁",
    desc: "Sort creatures into their correct animal classes in this science-meets-ESL challenge.",
    cover: "/assets/covers/animal-class-quest-cover.webp",
    tag: { label: "Science", color: "tag-bio" },
    badge: "Classify",
    difficulty: "Starter",
    barColor: "var(--teal)",
    hasComponent: true,
  },
  colourclash: {
    name: "Colour Clash",
    icon: "🎨",
    desc: "Identify and match colours at speed — great for early learners and visual thinkers.",
    cover: "/assets/covers/colour-clash-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Colours",
    difficulty: "Starter",
    barColor: "var(--purple)",
    hasComponent: true,
  },
  crimsonduel: {
    name: "Crimson Color Duel",
    icon: "⚔️",
    desc: "Two-player colour duel mode — compete head-to-head to name colours fastest.",
    cover: "/assets/covers/crimson-colour-duel-cover.webp",
    tag: { label: "Colours", color: "tag-vocab" },
    badge: "Duel",
    difficulty: "Competitive",
    barColor: "var(--red)",
    hasComponent: true,
  },
  deepseaReveal: {
    name: "Deep Sea Reveal",
    icon: "🌊",
    desc: "Uncover hidden ocean creatures as you answer vocabulary questions correctly.",
    cover: "/assets/covers/deep-sea-reveal.webp",
    tag: { label: "Science", color: "tag-bio" },
    badge: "Reveal",
    difficulty: "Mixed Skills",
    barColor: "var(--teal)",
    hasComponent: true,
  },
  emojimatch: {
    name: "Emoji Match",
    icon: "😊",
    desc: "Match emojis to their English words in this fun and expressive memory challenge.",
    cover: "/assets/covers/emoji-match-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Match Up",
    difficulty: "Starter",
    barColor: "var(--gold)",
    hasComponent: true,
  },
  emojispelling: {
    name: "Emoji Spelling Game",
    icon: "📝",
    desc: "Use emoji clues to practise spelling and reinforce word-sound connections.",
    cover: "/assets/covers/emoji-spelling-game-cover.webp",
    tag: { label: "Spelling", color: "tag-words" },
    badge: "Spell It",
    difficulty: "Intermediate",
    barColor: "var(--purple)",
    hasComponent: true,
  },
  familyquest: {
    name: "Family Quest",
    icon: "👨‍👩‍👧",
    desc: "Learn family member vocabulary and relationships through an interactive quest format.",
    cover: "/assets/covers/family-quest-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Family",
    difficulty: "Starter",
    barColor: "var(--green)",
    hasComponent: true,
  },
  farmgame: {
    name: "Farm Game",
    icon: "🌾",
    desc: "Explore farm life vocabulary through an engaging game-based learning experience.",
    cover: "/assets/covers/farm-game-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Farm Life",
    difficulty: "Starter",
    barColor: "var(--gold)",
    hasComponent: true,
  },
  findmyfood: {
    name: "Find My Food",
    icon: "🍔",
    desc: "Spot and identify foods from descriptions — builds food vocabulary and reading skills.",
    cover: "/assets/covers/find-my-food-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Find It",
    difficulty: "Starter",
    barColor: "var(--coral)",
    hasComponent: true,
  },
  flagmaster: {
    name: "Flagmaster",
    icon: "🚩",
    desc: "Identify world flags and their countries — a geography and culture vocabulary boost.",
    cover: "/assets/covers/flagmaster-cover.webp",
    tag: { label: "Geography", color: "tag-bio" },
    badge: "Flags",
    difficulty: "Intermediate",
    barColor: "var(--blue)",
    hasComponent: true,
  },
  foodwordhunt: {
    name: "Food Word Hunt",
    icon: "🍕",
    desc: "Hunt for hidden food words in a grid — combines spelling skills with vocabulary building.",
    cover: "/assets/covers/food-word-hunt-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Hunt",
    difficulty: "Puzzle",
    barColor: "var(--coral)",
    hasComponent: true,
  },
  fruitwordhunt: {
    name: "Fruit Word Hunt",
    icon: "🍎",
    desc: "Find fruit names hidden in a letter grid and sharpen your spelling at the same time.",
    cover: "/assets/covers/fruit-word-hunt-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Hunt",
    difficulty: "Puzzle",
    barColor: "var(--green)",
    hasComponent: true,
  },
  lakersracer: {
    name: "Lakers Showtime Racer",
    icon: "🏀",
    desc: "Race to the basket by answering correctly — fast-paced vocabulary and grammar sprints.",
    cover: "/assets/covers/shakers-showtime-racer-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Race",
    difficulty: "Competitive",
    barColor: "var(--gold)",
    hasComponent: true,
  },
  neonbridge: {
    name: "Neon Bridge of Destiny",
    icon: "🌉",
    desc: "Cross the neon bridge by choosing the correct answer before time runs out.",
    cover: "/assets/covers/neon-bridge-cover.webp",
    tag: { label: "Grammar", color: "tag-grammar" },
    badge: "Survive",
    difficulty: "Intermediate",
    barColor: "var(--purple)",
    hasComponent: true,
  },
  oceanquest: {
    name: "Ocean Quest",
    icon: "🐠",
    desc: "Dive into ocean science vocabulary with this colourful underwater classification quest.",
    cover: "/assets/covers/ocean-quest-cover.webp",
    tag: { label: "Science", color: "tag-bio" },
    badge: "Dive In",
    difficulty: "Mixed Skills",
    barColor: "var(--teal)",
    hasComponent: true,
  },
  pacman: {
    name: "Pac-Man",
    icon: "👾",
    desc: "Classic arcade action with an ESL twist — chomp your way through vocabulary challenges.",
    cover: "/assets/covers/pac-man-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Arcade",
    difficulty: "Arcade",
    barColor: "var(--gold)",
    hasComponent: true,
  },
  phonicsadventure: {
    name: "Phonics Adventure",
    icon: "📖",
    desc: "Go on a phonics journey, practising letter sounds and blends through story-driven play.",
    cover: "/assets/covers/phonics-adventure-cover.webp",
    tag: { label: "Phonics", color: "tag-words" },
    badge: "Phonics",
    difficulty: "Starter",
    barColor: "var(--blue)",
    hasComponent: true,
  },
  phonicsworld: {
    name: "Phonics World",
    icon: "🔤",
    desc: "Explore a world of letter-sound relationships — ideal for early readers building fluency.",
    cover: "/assets/covers/phonics-world-cover.webp",
    tag: { label: "Phonics", color: "tag-words" },
    badge: "Sounds",
    difficulty: "Starter",
    barColor: "var(--blue)",
    hasComponent: true,
  },
  shuttlecock: {
    name: "Shuttlecock Smash",
    icon: "🏸",
    desc: "Rally your vocabulary knowledge in this badminton-inspired word-smashing challenge.",
    cover: "/assets/covers/shuttlecock-smash-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Smash",
    difficulty: "Competitive",
    barColor: "var(--green)",
    hasComponent: true,
  },
  tornado: {
    name: "Tornado",
    icon: "🌪️",
    desc: "A whirlwind vocab challenge — answer before the storm sweeps your score away.",
    cover: "/assets/covers/tornado-cover.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Storm",
    difficulty: "Intermediate",
    barColor: "var(--red)",
    hasComponent: true,
  },
  wgrandprix: {
    name: "W Grand Prix",
    icon: "🏎️",
    desc: "Rev up your vocabulary and race to the finish — the faster you answer, the further you go.",
    cover: "/assets/covers/w-grand-prix.webp",
    tag: { label: "Vocabulary", color: "tag-vocab" },
    badge: "Race",
    difficulty: "Competitive",
    barColor: "var(--red)",
    hasComponent: true,
  },
  countadd: {
    name: "Count & Add",
    icon: "➕",
    desc: "Practise quick counting and addition with bright, early-numeracy questions.",
    cover: "/assets/covers/count-and-add-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Add Up",
    difficulty: "Starter",
    barColor: "var(--green)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/count-and-add/count-and-add.html",
  },
  moneyblocks: {
    name: "Money Blocks",
    icon: "💰",
    desc: "Reveal money blocks, manage risk, and race to build the biggest total.",
    cover: "/assets/covers/money-blocks-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Money",
    difficulty: "Mixed Skills",
    barColor: "var(--gold)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/money-blocks/index.html",
  },
  parachutedrop: {
    name: "Parachute Drop",
    icon: "🪂",
    desc: "Roll, stop, and choose parachute values in a playful two-player number game.",
    cover: "/assets/covers/parachute-drop-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Dice",
    difficulty: "Starter",
    barColor: "var(--blue)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/parachute-drop/index.html",
  },
  superwings: {
    name: "Super Wings Races",
    icon: "✈️",
    desc: "Race colourful planes around the board in a simple turn-based classroom game.",
    cover: "/assets/covers/super-wing-races-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Race",
    difficulty: "Starter",
    barColor: "var(--red)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/super-wings-game/index.html",
  },
  swampjump: {
    name: "Froggy Hop",
    icon: "🐸",
    desc: "Hop through the swamp, time each jump, and chase a new high score.",
    cover: "/assets/covers/froggy-hop-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Hop",
    difficulty: "Arcade",
    barColor: "var(--green)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/swamp-jump-game/index.html",
  },
  treasurechest: {
    name: "Treasure Chest Showdown",
    icon: "🏴‍☠️",
    desc: "Choose treasure chests, collect rewards, and compete for the biggest hoard.",
    cover: "/assets/covers/treasure-chest-showdown-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Treasure",
    difficulty: "Competitive",
    barColor: "var(--gold)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/treasure-chest-game/index.html",
  },
  unicornwings: {
    name: "Unicorn Wing Races",
    icon: "🦄",
    desc: "Race unicorns around the board with a sparkling two-player dice challenge.",
    cover: "/assets/covers/unicorn-wing-races-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Race",
    difficulty: "Starter",
    barColor: "var(--purple)",
    isNew: true,
    hasComponent: false,
    legacyUrl: "assets/legacy-games/unicorn-wings-game/index.html",
  },
  connect4: {
    name: "Connect 4",
    icon: "🔴",
    desc: "Classic four-in-a-row strategy — plan ahead and block your opponent to win.",
    cover: "/assets/covers/connect-4-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Strategy",
    difficulty: "Puzzle",
    barColor: "var(--blue)",
    hasComponent: true,
  },
  monkeytree: {
    name: "Monkey Tree Climb",
    icon: "🐒",
    desc: "Time your jumps and climb as high as you can in this quick-reflex arcade challenge.",
    cover: "/assets/covers/monkey-tree-climb-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Climb",
    difficulty: "Arcade",
    barColor: "var(--green)",
    hasComponent: true,
  },
  blockfight: {
    name: "Block Fight",
    icon: "⚔️",
    desc: "Face off in a fast-paced block-based battle that rewards quick thinking and sharp reflexes.",
    cover: "/assets/covers/block-fight-cover.webp",
    tag: { label: "Logic", color: "tag-bio" },
    badge: "Battle",
    difficulty: "Competitive",
    barColor: "var(--red)",
    hasComponent: true,
  },
};

export const GAME_KEYS = Object.keys(GAME_CATALOG);
export type GameKey = string;
export const GAME_ORDER = [...GAME_KEYS];
export const NEW_GAME_KEYS = GAME_KEYS.filter((id) => GAME_CATALOG[id].isNew);

// Derived flat lookups — kept so existing imports (GAME_NAMES, GAME_ICONS, etc.)
// don't need to change everywhere at once. These are 100% generated from
// GAME_CATALOG above; never edit them directly.
export const GAME_NAMES: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].name]));
export const GAME_ICONS: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].icon]));
export const GAME_DESC: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].desc]));
export const GAME_COVERS: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].cover]));
export const GAME_TAGS: Record<string, { label: string; color: string }> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].tag]));
export const GAME_BADGE: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].badge]));
export const GAME_DIFFICULTY: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].difficulty]));
export const GAME_BAR_COLOR: Record<string, string> = Object.fromEntries(GAME_KEYS.map((id) => [id, GAME_CATALOG[id].barColor]));
export const GAME_URLS: Record<string, string> = Object.fromEntries(GAME_KEYS.filter((id) => GAME_CATALOG[id].legacyUrl).map((id) => [id, GAME_CATALOG[id].legacyUrl as string]));
