// games/quiz-trail/data.js
// Question bank for Quiz Trail — 10 levels x 20 questions.
// Pulled straight from the original quiz.html prototype.

export const TOTAL_LEVELS = 10;
export const QUESTIONS_PER_LEVEL = 20;
export const MAX_LIVES = 3;

export const allQuestions = [
  // LEVEL 1
  {level:1, question:"What colour is the sky on a clear day?", answers:["Green","Blue","Red","Yellow"], correct:1},
  {level:1, question:"How many days are there in one week?", answers:["5","6","7","8"], correct:2},
  {level:1, question:'Which animal says "meow"?', answers:["Dog","Cow","Cat","Horse"], correct:2},
  {level:1, question:"Which planet do humans live on?", answers:["Mars","Earth","Venus","Jupiter"], correct:1},
  {level:1, question:"How many legs does a spider have?", answers:["6","8","10","12"], correct:1},
  {level:1, question:"Which fruit is usually yellow?", answers:["Apple","Banana","Orange","Strawberry"], correct:1},
  {level:1, question:"Which season comes after spring?", answers:["Winter","Autumn","Summer","Rainy"], correct:2},
  {level:1, question:"What is frozen water called?", answers:["Steam","Ice","Rain","Snow"], correct:1},
  {level:1, question:"Which animal is known as the King of the Jungle?", answers:["Tiger","Lion","Bear","Wolf"], correct:1},
  {level:1, question:"Which hand has the thumb?", answers:["Left only","Right only","Both hands","Neither"], correct:2},
  {level:1, question:"How many hours are there in a day?", answers:["12","18","24","30"], correct:2},
  {level:1, question:"Which bird cannot fly?", answers:["Eagle","Penguin","Hawk","Sparrow"], correct:1},
  {level:1, question:"Which ocean is the largest?", answers:["Atlantic","Indian","Pacific","Arctic"], correct:2},
  {level:1, question:"Which shape has three sides?", answers:["Square","Triangle","Circle","Rectangle"], correct:1},
  {level:1, question:"What do bees make?", answers:["Butter","Honey","Cheese","Milk"], correct:1},
  {level:1, question:"Which animal has a long trunk?", answers:["Rhino","Elephant","Hippo","Camel"], correct:1},
  {level:1, question:"What is 5 + 5?", answers:["8","9","10","11"], correct:2},
  {level:1, question:"Which colour do you get by mixing red and blue?", answers:["Green","Purple","Orange","Brown"], correct:1},
  {level:1, question:"Which month has Christmas?", answers:["July","October","December","February"], correct:2},
  {level:1, question:"Which is the tallest animal?", answers:["Elephant","Giraffe","Camel","Horse"], correct:1},
  // LEVEL 2
  {level:2, question:"Which country is famous for pizza?", answers:["France","Italy","Spain","Greece"], correct:1},
  {level:2, question:"What is the capital of Japan?", answers:["Beijing","Tokyo","Seoul","Bangkok"], correct:1},
  {level:2, question:"Which mammal can fly?", answers:["Eagle","Bat","Penguin","Ostrich"], correct:1},
  {level:2, question:"Which gas do humans breathe in?", answers:["Nitrogen","Oxygen","Helium","Carbon Dioxide"], correct:1},
  {level:2, question:"Which is the largest planet?", answers:["Earth","Saturn","Jupiter","Neptune"], correct:2},
  {level:2, question:"Which continent is Egypt in?", answers:["Europe","Asia","Africa","South America"], correct:2},
  {level:2, question:"Which instrument has 88 keys?", answers:["Guitar","Piano","Violin","Trumpet"], correct:1},
  {level:2, question:"Which animal is famous for black and white stripes?", answers:["Tiger","Zebra","Horse","Leopard"], correct:1},
  {level:2, question:"Which metal is most commonly used to make cans?", answers:["Gold","Aluminium","Silver","Copper"], correct:1},
  {level:2, question:"Which language is spoken in Brazil?", answers:["Spanish","Portuguese","French","Italian"], correct:1},
  {level:2, question:"Which is the smallest continent?", answers:["Europe","Australia","Antarctica","South America"], correct:1},
  {level:2, question:"What is the boiling point of water (°C)?", answers:["50","75","100","150"], correct:2},
  {level:2, question:"Which animal lays the largest eggs?", answers:["Chicken","Ostrich","Eagle","Duck"], correct:1},
  {level:2, question:"Which sport uses a racket?", answers:["Football","Tennis","Rugby","Cricket"], correct:1},
  {level:2, question:"Which planet is known as the Red Planet?", answers:["Venus","Mars","Mercury","Saturn"], correct:1},
  {level:2, question:"Which is the longest river in Africa?", answers:["Congo","Nile","Niger","Zambezi"], correct:1},
  {level:2, question:"Which is the hardest natural substance?", answers:["Gold","Diamond","Iron","Quartz"], correct:1},
  {level:2, question:"What do pandas mainly eat?", answers:["Grass","Bamboo","Fish","Leaves"], correct:1},
  {level:2, question:"Which country has the maple leaf on its flag?", answers:["USA","Canada","Australia","Norway"], correct:1},
  {level:2, question:"Which ocean lies between Africa and Australia?", answers:["Pacific","Atlantic","Indian","Arctic"], correct:2},
  // LEVEL 3
  {level:3, question:"What is the longest river in the world?", answers:["Amazon","Nile","Yangtze","Mississippi"], correct:0},
  {level:3, question:'Which element is represented by the symbol "O"?', answers:["Gold","Oxygen","Osmium","Oganesson"], correct:1},
  {level:3, question:"In which year did World War II end?", answers:["1943","1944","1945","1946"], correct:2},
  {level:3, question:"What is the capital of Australia?", answers:["Sydney","Melbourne","Canberra","Brisbane"], correct:2},
  {level:3, question:"Who painted the Mona Lisa?", answers:["Michelangelo","Raphael","Leonardo da Vinci","Donatello"], correct:2},
  {level:3, question:"Which is the largest desert in the world?", answers:["Sahara","Arabian","Antarctic","Gobi"], correct:2},
  {level:3, question:'What does the "www" stand for in a website URL?', answers:["World Wide Web","World Web Window","Wide World Web","Web World Wide"], correct:0},
  {level:3, question:"How many bones are in the adult human body?", answers:["186","196","206","216"], correct:2},
  {level:3, question:"Which country gifted the Statue of Liberty to the USA?", answers:["Britain","France","Spain","Germany"], correct:1},
  {level:3, question:"What is the chemical formula for water?", answers:["CO2","H2O","NaCl","O2"], correct:1},
  {level:3, question:"Which sport is played at Wimbledon?", answers:["Cricket","Tennis","Golf","Rugby"], correct:1},
  {level:3, question:"What is the fastest land animal?", answers:["Lion","Cheetah","Gazelle","Horse"], correct:1},
  {level:3, question:"Who was the first person to walk on the Moon?", answers:["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","Michael Collins"], correct:1},
  {level:3, question:"Which of these is NOT a primary color of light?", answers:["Red","Green","Blue","Yellow"], correct:3},
  {level:3, question:"What is the currency of the United Kingdom?", answers:["Euro","Dollar","Pound","Franc"], correct:2},
  {level:3, question:"How many players are on a standard soccer team on the field?", answers:["9","10","11","12"], correct:2},
  {level:3, question:"Which ocean is the Bermuda Triangle located in?", answers:["Pacific","Atlantic","Indian","Arctic"], correct:1},
  {level:3, question:"What is the hardest natural substance on Earth?", answers:["Quartz","Diamond","Topaz","Corundum"], correct:1},
  {level:3, question:'Who wrote "The Odyssey"?', answers:["Virgil","Homer","Sophocles","Aristotle"], correct:1},
  {level:3, question:"What does a thermometer measure?", answers:["Pressure","Humidity","Temperature","Wind Speed"], correct:2},
  // LEVEL 4
  {level:4, question:"Which country has the largest population in the world?", answers:["USA","Indonesia","India","Brazil"], correct:2},
  {level:4, question:"What is the SI unit of electric current?", answers:["Volt","Watt","Ampere","Ohm"], correct:2},
  {level:4, question:"In which city is the United Nations headquarters located?", answers:["Geneva","New York City","Vienna","Paris"], correct:1},
  {level:4, question:"Which planet has the most moons in our Solar System?", answers:["Jupiter","Saturn","Uranus","Neptune"], correct:1},
  {level:4, question:"What is the capital of Canada?", answers:["Toronto","Vancouver","Ottawa","Montreal"], correct:2},
  {level:4, question:"Who formulated the law of universal gravitation?", answers:["Galileo Galilei","Isaac Newton","Albert Einstein","Johannes Kepler"], correct:1},
  {level:4, question:'Which element has the chemical symbol "Fe"?', answers:["Fluorine","Iron","Francium","Fermium"], correct:1},
  {level:4, question:"What is the largest organ in the human body?", answers:["Liver","Brain","Skin","Heart"], correct:2},
  {level:4, question:"Which famous scientist developed the theory of relativity?", answers:["Isaac Newton","Albert Einstein","Niels Bohr","Stephen Hawking"], correct:1},
  {level:4, question:"In which year did the Titanic sink?", answers:["1910","1911","1912","1913"], correct:2},
  {level:4, question:"What is the most abundant gas in Earth's atmosphere?", answers:["Oxygen","Nitrogen","Carbon Dioxide","Argon"], correct:1},
  {level:4, question:'Which country is known as the "Land of the Rising Sun"?', answers:["China","South Korea","Japan","Thailand"], correct:2},
  {level:4, question:"How many strings does a standard violin have?", answers:["3","4","5","6"], correct:1},
  {level:4, question:"What type of animal is a Komodo dragon?", answers:["Mammal","Amphibian","Reptile","Fish"], correct:2},
  {level:4, question:"Which river has the greatest volume of water?", answers:["Nile","Amazon","Yangtze","Mississippi"], correct:1},
  {level:4, question:"What is the speed of light in a vacuum (approx.)?", answers:["300,000 km/s","150,000 km/s","500,000 km/s","1,000,000 km/s"], correct:0},
  {level:4, question:"Who was the first female prime minister of the UK?", answers:["Theresa May","Margaret Thatcher","Indira Gandhi","Angela Merkel"], correct:1},
  {level:4, question:"Which of these metals is liquid at room temperature?", answers:["Iron","Copper","Mercury","Silver"], correct:2},
  {level:4, question:"What is the largest island in the world?", answers:["Madagascar","Borneo","Greenland","New Guinea"], correct:2},
  {level:4, question:'In which sport would you perform a "slam dunk"?', answers:["Volleyball","Basketball","Tennis","Badminton"], correct:1},
  // LEVEL 5
  {level:5, question:"Which country is known as the Land of the Rising Sun?", answers:["China","Japan","South Korea","Thailand"], correct:1},
  {level:5, question:"Which famous ship sank in 1912 after hitting an iceberg?", answers:["Lusitania","Titanic","Britannic","Queen Mary"], correct:1},
  {level:5, question:"What is the largest organ in the human body?", answers:["Liver","Skin","Brain","Lungs"], correct:1},
  {level:5, question:'Which element has the chemical symbol "Fe"?', answers:["Fluorine","Iron","Lead","Zinc"], correct:1},
  {level:5, question:"Which continent contains the Amazon Rainforest?", answers:["Africa","South America","Asia","Europe"], correct:1},
  {level:5, question:"Who wrote Romeo and Juliet?", answers:["Charles Dickens","William Shakespeare","Jane Austen","Mark Twain"], correct:1},
  {level:5, question:"Which is the smallest country in the world?", answers:["Monaco","Vatican City","Luxembourg","Malta"], correct:1},
  {level:5, question:'Which sport is known as "the beautiful game"?', answers:["Basketball","Football (Soccer)","Rugby","Cricket"], correct:1},
  {level:5, question:"Which planet is famous for its rings?", answers:["Mars","Saturn","Uranus","Neptune"], correct:1},
  {level:5, question:"Which famous scientist discovered gravity after observing a falling apple?", answers:["Albert Einstein","Isaac Newton","Galileo Galilei","Nikola Tesla"], correct:1},
  {level:5, question:"Which country is famous for the pyramids?", answers:["Peru","Egypt","Mexico","Jordan"], correct:1},
  {level:5, question:"Which bird is the symbol of the United States?", answers:["Falcon","Bald Eagle","Hawk","Owl"], correct:1},
  {level:5, question:"What is the capital city of Spain?", answers:["Barcelona","Madrid","Seville","Valencia"], correct:1},
  {level:5, question:"Which is the largest species of penguin?", answers:["Emperor Penguin","King Penguin","Gentoo Penguin","Adelie Penguin"], correct:0},
  {level:5, question:"Which ocean borders the east coast of the United States?", answers:["Pacific","Atlantic","Indian","Arctic"], correct:1},
  {level:5, question:"Which instrument is used to measure earthquakes?", answers:["Thermometer","Seismograph","Barometer","Hygrometer"], correct:1},
  {level:5, question:"Which vitamin is mainly found in citrus fruits?", answers:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"], correct:2},
  {level:5, question:"Which famous tower is found in Paris?", answers:["Leaning Tower of Pisa","Eiffel Tower","Big Ben","CN Tower"], correct:1},
  {level:5, question:"Which country has the largest population in Africa?", answers:["Egypt","Nigeria","Ethiopia","South Africa"], correct:1},
  {level:5, question:"Which gas makes up about 78% of Earth's atmosphere?", answers:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"], correct:1},
  // LEVEL 6
  {level:6, question:"Which country has the largest number of islands?", answers:["Indonesia","Sweden","Canada","Philippines"], correct:1},
  {level:6, question:"What is the SI unit of pressure?", answers:["Newton","Joule","Pascal","Watt"], correct:2},
  {level:6, question:"Who discovered the circulation of blood?", answers:["Galen","William Harvey","Andreas Vesalius","Hippocrates"], correct:1},
  {level:6, question:"Which language has the most native speakers worldwide?", answers:["English","Mandarin Chinese","Spanish","Hindi"], correct:1},
  {level:6, question:"What is the capital of Turkey?", answers:["Istanbul","Ankara","Izmir","Antalya"], correct:1},
  {level:6, question:"Which explorer led the first expedition to circumnavigate the globe?", answers:["Christopher Columbus","Ferdinand Magellan","Vasco da Gama","James Cook"], correct:1},
  {level:6, question:"What type of bond holds water molecules together?", answers:["Ionic bond","Covalent bond","Hydrogen bond","Metallic bond"], correct:1},
  {level:6, question:"Which country was the first to launch a satellite into space?", answers:["USA","Soviet Union","China","France"], correct:1},
  {level:6, question:"What is the largest artery in the human body?", answers:["Pulmonary artery","Aorta","Carotid artery","Femoral artery"], correct:1},
  {level:6, question:'Who composed the "Moonlight Sonata"?', answers:["Mozart","Bach","Beethoven","Chopin"], correct:2},
  {level:6, question:"Which of these countries is NOT in the Southern Hemisphere?", answers:["Australia","Brazil","Mexico","South Africa"], correct:2},
  {level:6, question:"What is the chemical symbol for tungsten?", answers:["Tu","Tg","W","Tn"], correct:2},
  {level:6, question:"How many chambers does the human heart have?", answers:["2","3","4","5"], correct:2},
  {level:6, question:"Which ancient wonder was located in Alexandria, Egypt?", answers:["Colossus","Lighthouse","Hanging Gardens","Temple of Artemis"], correct:1},
  {level:6, question:"What is the most spoken language in South America?", answers:["English","Portuguese","Spanish","French"], correct:2},
  {level:6, question:"Which element is essential for thyroid function?", answers:["Calcium","Iron","Iodine","Zinc"], correct:2},
  {level:6, question:'Who wrote "The Canterbury Tales"?', answers:["Geoffrey Chaucer","John Milton","William Blake","Edmund Spenser"], correct:0},
  {level:6, question:"What is the hottest planet in our Solar System?", answers:["Mercury","Venus","Mars","Jupiter"], correct:1},
  {level:6, question:"Which country has the longest coastline in the world?", answers:["Australia","Canada","Russia","Indonesia"], correct:1},
  {level:6, question:"What is the powerhouse of the cell?", answers:["Nucleus","Ribosome","Mitochondria","Endoplasmic Reticulum"], correct:2},
  // LEVEL 7
  {level:7, question:"Which country has the most active volcanoes?", answers:["Japan","Indonesia","USA","Iceland"], correct:1},
  {level:7, question:"What is the rarest blood type?", answers:["A negative","B negative","AB negative","O negative"], correct:2},
  {level:7, question:"Which treaty ended World War I?", answers:["Treaty of Paris","Treaty of Versailles","Treaty of Vienna","Treaty of Ghent"], correct:1},
  {level:7, question:"Who developed the periodic table?", answers:["John Dalton","Dmitri Mendeleev","Antoine Lavoisier","Robert Boyle"], correct:1},
  {level:7, question:"What is the capital of Mongolia?", answers:["Astana","Ulaanbaatar","Bishkek","Tashkent"], correct:1},
  {level:7, question:"Which of these is the heaviest snake?", answers:["Reticulated Python","Green Anaconda","Burmese Python","King Cobra"], correct:1},
  {level:7, question:"What is the pH of pure water?", answers:["5","6","7","8"], correct:2},
  {level:7, question:'Who painted "The Starry Night"?', answers:["Claude Monet","Vincent van Gogh","Paul Cézanne","Edgar Degas"], correct:1},
  {level:7, question:"Which country is the largest producer of olive oil?", answers:["Italy","Greece","Spain","Turkey"], correct:2},
  {level:7, question:"What is the speed of sound in air (approx.)?", answers:["343 m/s","543 m/s","743 m/s","943 m/s"], correct:0},
  {level:7, question:"Which ancient civilization built Machu Picchu?", answers:["Aztec","Maya","Inca","Olmec"], correct:2},
  {level:7, question:"What is the largest moon of Saturn?", answers:["Europa","Titan","Ganymede","Callisto"], correct:1},
  {level:7, question:'Who wrote "1984"?', answers:["Aldous Huxley","George Orwell","Ray Bradbury","H.G. Wells"], correct:1},
  {level:7, question:"Which country has the world's largest proven oil reserves?", answers:["Saudi Arabia","Venezuela","Canada","Russia"], correct:1},
  {level:7, question:"What type of animal is a platypus?", answers:["Reptile","Bird","Mammal","Amphibian"], correct:2},
  {level:7, question:"How many elements are in the periodic table (as of 2024)?", answers:["112","116","118","120"], correct:2},
  {level:7, question:"Which country won the first FIFA World Cup in 1930?", answers:["Argentina","Brazil","Uruguay","Italy"], correct:2},
  {level:7, question:"What is the largest saltwater lake in the world?", answers:["Lake Baikal","Caspian Sea","Lake Superior","Dead Sea"], correct:1},
  {level:7, question:"Who discovered the electron?", answers:["Ernest Rutherford","J.J. Thomson","James Chadwick","Niels Bohr"], correct:1},
  {level:7, question:"What is the capital of New Zealand?", answers:["Auckland","Christchurch","Wellington","Hamilton"], correct:2},
  // LEVEL 8
  {level:8, question:"Which country has the most official languages?", answers:["India","Zimbabwe","South Africa","Switzerland"], correct:1},
  {level:8, question:"What is the largest known prime number (as of 2024) known as?", answers:["Fermat prime","Mersenne prime","Sophie Germain prime","Eisenstein prime"], correct:1},
  {level:8, question:"Which sea is the largest body of seawater with the highest salinity?", answers:["Dead Sea","Red Sea","Mediterranean Sea","Black Sea"], correct:1},
  {level:8, question:'Who wrote "One Hundred Years of Solitude"?', answers:["Jorge Luis Borges","Gabriel García Márquez","Pablo Neruda","Mario Vargas Llosa"], correct:1},
  {level:8, question:"What is the largest Mediterranean island?", answers:["Crete","Cyprus","Sicily","Sardinia"], correct:2},
  {level:8, question:"Which country is home to the world's largest mangrove forest?", answers:["India","Bangladesh","Brazil","Indonesia"], correct:1},
  {level:8, question:"What is the SI unit of luminous intensity?", answers:["Lumen","Lux","Candela","Watt"], correct:2},
  {level:8, question:"Which treaty ended the Thirty Years' War?", answers:["Treaty of Utrecht","Peace of Westphalia","Treaty of Paris","Congress of Vienna"], correct:1},
  {level:8, question:"What element has the atomic number 74?", answers:["Tantalum","Tungsten","Rhenium","Osmium"], correct:1},
  {level:8, question:"Which country has the world's highest average elevation?", answers:["Nepal","Bhutan","Tajikistan","Kyrgyzstan"], correct:1},
  {level:8, question:"Which moon of Jupiter has the smoothest known surface?", answers:["Io","Europa","Ganymede","Callisto"], correct:1},
  {level:8, question:"Who was the first emperor of China?", answers:["Qin Shi Huang","Han Wudi","Tang Taizong","Kublai Khan"], correct:0},
  {level:8, question:"What is the second most abundant element in the Earth's crust?", answers:["Oxygen","Silicon","Aluminum","Iron"], correct:1},
  {level:8, question:"Which country is the largest producer of saffron?", answers:["India","Spain","Iran","Morocco"], correct:2},
  {level:8, question:"Who developed the theory of evolution by natural selection?", answers:["Jean-Baptiste Lamarck","Charles Darwin","Alfred Russel Wallace","Both Darwin and Wallace"], correct:3},
  {level:8, question:"What is the name of the galaxy closest to the Milky Way?", answers:["Triangulum Galaxy","Andromeda Galaxy","Sombrero Galaxy","Whirlpool Galaxy"], correct:1},
  {level:8, question:"Which element has the highest electrical conductivity?", answers:["Copper","Gold","Silver","Aluminum"], correct:2},
  {level:8, question:'Who painted "The Scream"?', answers:["Vincent van Gogh","Edvard Munch","Pablo Picasso","Salvador Dalí"], correct:1},
  {level:8, question:"What is the deepest point in the ocean?", answers:["Tonga Trench","Mariana Trench","Philippine Trench","Java Trench"], correct:1},
  {level:8, question:"Which country was the first to legalize same-sex marriage?", answers:["Canada","Netherlands","Belgium","Spain"], correct:1},
  // LEVEL 9
  {level:9, question:"Which Nobel Prize-winning physicist discovered the neutron?", answers:["Ernest Rutherford","James Chadwick","Niels Bohr","Enrico Fermi"], correct:1},
  {level:9, question:"What is the highest mountain outside Asia?", answers:["Mount Kilimanjaro","Aconcagua","Mount McKinley (Denali)","Mount Elbrus"], correct:1},
  {level:9, question:"Which country is the world's largest producer of lithium?", answers:["Chile","Australia","Bolivia","Argentina"], correct:1},
  {level:9, question:"What is the rarest naturally occurring noble gas?", answers:["Neon","Krypton","Xenon","Radon"], correct:2},
  {level:9, question:"Which independent republic is completely surrounded by Italy?", answers:["Vatican City","San Marino","Monaco","Liechtenstein"], correct:1},
  {level:9, question:"Who formulated the three laws of motion?", answers:["Galileo Galilei","Isaac Newton","René Descartes","Albert Einstein"], correct:1},
  {level:9, question:"What is the chemical symbol for antimony?", answers:["An","At","Sb","Am"], correct:2},
  {level:9, question:"Which of these countries does NOT border the Black Sea?", answers:["Romania","Bulgaria","Serbia","Ukraine"], correct:2},
  {level:9, question:"What is the capital of Burkina Faso?", answers:["Bamako","Ouagadougou","Niamey","Dakar"], correct:1},
  {level:9, question:"Who discovered penicillin?", answers:["Joseph Lister","Alexander Fleming","Louis Pasteur","Robert Koch"], correct:1},
  {level:9, question:"Which planet rotates on its side?", answers:["Venus","Uranus","Neptune","Saturn"], correct:1},
  {level:9, question:"What is the largest bone in the human body?", answers:["Tibia","Femur","Pelvis","Skull"], correct:1},
  {level:9, question:"Which country was the last to host both Summer and Winter Olympics?", answers:["USA","China","Japan","South Korea"], correct:1},
  {level:9, question:'Who wrote "The Prince"?', answers:["Thomas More","Niccolò Machiavelli","Desiderius Erasmus","Baldassare Castiglione"], correct:1},
  {level:9, question:"What is the main component of natural gas?", answers:["Ethane","Propane","Methane","Butane"], correct:2},
  {level:9, question:"Which country has the world's oldest continuous constitution?", answers:["UK","USA","France","Sweden"], correct:1},
  {level:9, question:"What is the atomic number of uranium?", answers:["90","91","92","93"], correct:2},
  {level:9, question:"Which desert is the driest non-polar desert in the world?", answers:["Sahara","Atacama","Gobi","Kalahari"], correct:1},
  {level:9, question:'Who composed the "Brandenburg Concertos"?', answers:["Beethoven","Mozart","Bach","Handel"], correct:2},
  {level:9, question:"What is the currency of Switzerland?", answers:["Euro","Swiss Franc","Swiss Dollar","Swiss Mark"], correct:1},
  // LEVEL 10
  {level:10, question:"Which country has the highest number of UNESCO World Heritage Sites?", answers:["China","Italy","Spain","France"], correct:1},
  {level:10, question:"Which element has the highest melting point of all pure metals?", answers:["Iron","Tungsten","Titanium","Platinum"], correct:1},
  {level:10, question:"Which is the oldest continuously inhabited capital city in the world?", answers:["Athens","Damascus","Rome","Jerusalem"], correct:1},
  {level:10, question:'Which mathematician is known as the "Father of Geometry"?', answers:["Pythagoras","Euclid","Archimedes","Euler"], correct:1},
  {level:10, question:"Which planet has the largest volcano in the Solar System?", answers:["Venus","Mars","Jupiter","Mercury"], correct:1},
  {level:10, question:"Which country was the first to grant women the right to vote in national elections?", answers:["Australia","New Zealand","Finland","Norway"], correct:1},
  {level:10, question:'Which famous document begins with the words "We the People"?', answers:["Magna Carta","United States Constitution","Declaration of Independence","Bill of Rights"], correct:1},
  {level:10, question:"Which is the world's largest coral reef system?", answers:["Belize Barrier Reef","Great Barrier Reef","Red Sea Coral Reef","New Caledonia Barrier Reef"], correct:1},
  {level:10, question:"What is the SI unit of force?", answers:["Joule","Newton","Watt","Pascal"], correct:1},
  {level:10, question:"Which country has the largest proven natural gas reserves?", answers:["United States","Russia","Iran","Qatar"], correct:1},
  {level:10, question:"Which Roman emperor was the first to convert to Christianity?", answers:["Augustus","Constantine the Great","Nero","Hadrian"], correct:1},
  {level:10, question:"Which famous scientist proposed the heliocentric model of the Solar System?", answers:["Galileo Galilei","Nicolaus Copernicus","Johannes Kepler","Tycho Brahe"], correct:1},
  {level:10, question:"Which is the deepest lake in the world?", answers:["Lake Tanganyika","Lake Baikal","Caspian Sea","Lake Superior"], correct:1},
  {level:10, question:"Which country has the longest railway network in the world?", answers:["China","Russia","United States","India"], correct:2},
  {level:10, question:"Which artist painted the ceiling of the Sistine Chapel?", answers:["Leonardo da Vinci","Raphael","Michelangelo","Donatello"], correct:2},
  {level:10, question:"Which country hosted the first modern Olympic Games in 1896?", answers:["France","Greece","Italy","United Kingdom"], correct:1},
  {level:10, question:"Which country has the world's largest proven lithium reserves?", answers:["Chile","Australia","Bolivia","Argentina"], correct:2},
  {level:10, question:"Which is the smallest prime number?", answers:["0","1","2","3"], correct:2},
  {level:10, question:"Which language was the official language of the Roman Empire?", answers:["Greek","Latin","Italian","French"], correct:1},
  {level:10, question:"Which spacecraft was the first to land humans on the Moon?", answers:["Apollo 10","Apollo 11","Apollo 12","Apollo 13"], correct:1},
];
