const question = (id, text, options, answer, page) => ({ id, question: text, options, answer, page });

export const READING_RESCUE_QUIZZES = {
  2: [
    question('l2-q1', 'Where was Finn walking when he heard a tiny “Peep! Peep!”?', ['Through the Whispering Woods', 'Beside the Whispering River', 'Across a green meadow', 'Near the old oak tree'], 'B', 1),
    question('l2-q2', 'What was the duckling’s name?', ['Daisy', 'Ruby', 'Toby', 'Luna'], 'A', 1),
    question('l2-q3', 'What clue did Finn notice near the riverbank?', ['A broken branch', 'A red flower', 'Wet footprints', 'A blue feather'], 'C', 1),
    question('l2-q4', 'What did Finn and Daisy find along the path?', ['Small yellow feathers', 'Three large rocks', 'A basket of food', 'A family of frogs'], 'A', 2),
    question('l2-q5', 'Where did the footprints lead after the tall grass?', ['Toward the mountains', 'Toward a wooden bridge', 'Toward a deep cave', 'Toward the river'], 'B', 2),
    question('l2-q6', 'What did Finn discover at the pond?', ['Daisy’s family', 'A group of ducks', 'A family of rabbits', 'A group of frogs'], 'D', 3),
    question('l2-q7', 'Which clue showed Finn that the duck family had gone toward the old oak tree?', ['The sound of frogs', 'The footprints', 'The wooden bridge', 'The green meadow'], 'B', 3),
    question('l2-q8', 'What did Daisy remember about the narrow path?', ['Her family used it when visiting the pond.', 'She had never seen it before.', 'It led to the mountains.', 'It was where she found the red flower.'], 'A', 4),
    question('l2-q9', 'Who did Daisy find beside the pond?', ['Finn and the frogs', 'Her mother, father, and three ducklings', 'Ruby’s family', 'A group of birds'], 'B', 4),
    question('l2-q10', 'What lesson did Finn share at the end of the story?', ['Always stay beside the river.', 'Never explore the forest.', 'Looking carefully and asking for help can make a big difference.', 'Animals should never travel alone.'], 'C', 5),
  ],
  3: [
    question('l3-q1', 'Where was Finn exploring when he heard someone calling for help?', ['The Whispering Woods', 'The green meadow', 'The riverbank', 'The old oak tree'], 'A', 1),
    question('l3-q2', 'Why could Ruby not get out?', ['She was stuck in a pond.', 'She was trapped beneath a fallen branch.', 'She had fallen into a hole.', 'She was caught in some vines.'], 'B', 1),
    question('l3-q3', 'Why did Finn know he needed a plan?', ['He could not find Ruby’s family.', 'The forest was too dark.', 'The branch was too heavy to move by himself.', 'Ruby did not know where she was.'], 'C', 1),
    question('l3-q4', 'What did Finn find hanging from a nearby tree?', ['A wooden bridge', 'Strong vines', 'Yellow feathers', 'A basket'], 'B', 2),
    question('l3-q5', 'What other useful object did Finn find?', ['A wooden log', 'A large stone', 'A rope bridge', 'A tree branch'], 'A', 2),
    question('l3-q6', 'How did Finn use the wooden log?', ['He used it as a bridge.', 'He used it to block the river.', 'He used it like a lever.', 'He used it to build a shelter.'], 'C', 3),
    question('l3-q7', 'What happened during the first rescue attempt?', ['Ruby escaped immediately.', 'The vine broke.', 'The branch slipped back into place.', 'Finn lost the wooden log.'], 'C', 3),
    question('l3-q8', 'What did Finn change when he tried again?', ['He moved the wooden log farther underneath the branch.', 'He found a different rabbit.', 'He used a smaller vine.', 'He moved the branch toward the river.'], 'A', 3),
    question('l3-q9', 'What did Ruby do after she became free?', ['She ran toward the river.', 'She hopped around happily.', 'She climbed the tree.', 'She went to sleep.'], 'B', 4),
    question('l3-q10', 'What did Finn say people should do when there is a problem?', ['Run away quickly.', 'Wait for someone else to solve it.', 'Stop, look carefully, and think about what to do.', 'Try the same thing again and again.'], 'C', 4),
  ],
  4: [
    question('l4-q1', 'What did Finn notice about the forest that morning?', ['It was unusually quiet.', 'It was unusually busy.', 'It was covered in snow.', 'It was completely empty.'], 'B', 1),
    question('l4-q2', 'Which animal was Finn collecting acorns?', ['A rabbit', 'A deer', 'A squirrel', 'A bird'], 'C', 1),
    question('l4-q3', 'Who did Finn find sitting beside a large rock?', ['Toby the bear cub', 'Ruby the rabbit', 'Daisy the duckling', 'A young deer'], 'A', 1),
    question('l4-q4', 'What had Toby been doing when he became separated from his family?', ['Collecting acorns', 'Swimming in the river', 'Looking at butterflies', 'Building a nest'], 'C', 2),
    question('l4-q5', 'What did Finn first notice in the soft mud?', ['Tiny deer tracks', 'Large paw prints', 'Bird feathers', 'Rabbit footprints'], 'B', 2),
    question('l4-q6', 'Why did Finn decide that the blue feather was not an important clue?', ['It was too small.', 'It was wet.', 'Toby said it did not belong to his family.', 'It was beside the river.'], 'C', 2),
    question('l4-q7', 'Which of the three paths had large bear paw prints?', ['The mountain path', 'The stream path', 'The path through the thick trees', 'The path beside the river'], 'C', 3),
    question('l4-q8', 'Who did Toby hear calling his name?', ['His sister', 'His father', 'Finn', 'A squirrel'], 'B', 3),
    question('l4-q9', 'What did Toby’s family say when they found him?', ['They were angry with him.', 'They had been looking everywhere for him.', 'They wanted him to stay with Finn.', 'They were going home without him.'], 'B', 4),
    question('l4-q10', 'What important idea did Finn learn at the end?', ['Only animals from the same family can help each other.', 'The forest belongs only to bears.', 'Families should always stay in one place.', 'Kindness can connect different families and animals.'], 'D', 5),
  ],
  5: [
    question('l5-q1', 'What had happened to the small wooden bridge?', ['It had been washed away.', 'Animals had broken it.', 'A storm had knocked branches onto it.', 'Finn had removed it.'], 'C', 1),
    question('l5-q2', 'Which three young animals were stranded across the river?', ['Toby, Ruby, and Daisy', 'Finn, Toby, and Ruby', 'Daisy, Ruby, and Luna', 'Toby, Daisy, and a deer'], 'A', 1),
    question('l5-q3', 'Why was the river dangerous?', ['It was frozen.', 'The water was moving quickly because of the rain.', 'It was full of rocks.', 'The bridge was too long.'], 'B', 1),
    question('l5-q4', 'What did Finn discover farther down the river?', ['A group of boats', 'A second wooden bridge', 'Large stepping stones', 'A deep cave'], 'C', 2),
    question('l5-q5', 'Why could Daisy not use the stepping stones?', ['She was too small to jump from stone to stone.', 'She did not know how to swim.', 'She was afraid of Toby.', 'The stones were too far from the river.'], 'A', 2),
    question('l5-q6', 'What did Finn use as a bridge?', ['A group of vines', 'A fallen tree trunk', 'The old wooden bridge', 'Several large rocks'], 'B', 2),
    question('l5-q7', 'What happened when Toby was crossing the tree trunk?', ['He fell into the river.', 'The vine broke.', 'A strong gust of wind shook the trees.', 'Daisy called him back.'], 'C', 3),
    question('l5-q8', 'What advice did Finn give Toby when he became frightened?', ['Jump quickly to the other side.', 'Close his eyes and wait.', 'Go back and find another path.', 'Look at Finn and take one small step at a time.'], 'D', 3),
    question('l5-q9', 'Why did Finn lead the animals toward a safe clearing?', ['The animals wanted to play there.', 'The river was rising quickly.', 'The clearing had more food.', 'Finn wanted to go home.'], 'B', 4),
    question('l5-q10', 'According to Finn, what makes a good leader?', ['Being the strongest animal.', 'Being the loudest animal.', 'Staying calm, listening, making a plan, and helping everyone work together.', 'Doing everything alone.'], 'C', 5),
  ],
};
