export const COMING_SOON_GAME_IDS = new Set([
  'animalAdventureRace',
  'archersduel',
  'blockfight',
  'bubblepop',
  'crimsonduel',
  'deepseaReveal',
  'dragonslingshot',
  'feedmonster',
  'fishingnumbers',
  'swampjump',
  'hiddencolours',
  'lakersracer',
  'monkeytree',
  'monsterbound',
  'neonbridge',
  'pacman',
  'picturerace',
  'tankwars',
  'unicorn',
  'turbodash',
  'superwings',
  'pluralquest',
  'quiztrail',
  'shuttlecock',
  'tonguetwister',
  'treasurechest',
  'unicornwings',
  'victoryvet',
  'volcanoracer',
  'wgrandprix',
  'wordfusion',
  'shapebuilder',
]);

export function canAccessGame(gameId: string) {
  return !COMING_SOON_GAME_IDS.has(gameId);
}
